# Generated by Django 5.0.9 on 2024-11-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0006_alter_route_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='key',
            field=models.TextField(blank=True, help_text='Add any random characters of your choice to shorten it.', unique=True),
        ),
    ]
